services:
  - type: web
    name: autoclaim
    env: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: BOT_TOKEN
        fromEnvVar: BOT_TOKEN
      - key: CHAT_ID
        fromEnvVar: CHAT_ID
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: true
